### ISSUE TITLE
Video on CSX

### ISSUE THREAD

**Issue by nelsonic** [jxnblk/jxnblk.github.io#14]
Hi @jxnblk,
The video on: http://jxnblk.com/cxs/
displays: 
![cxs-video-not-allowed](https://cloud.githubusercontent.com/assets/194400/20177392/6a8ac12a-a744-11e6-8cf1-bb74268d3bb1.png)
It's not an embedding issue as Attempting to view it on YouTube: https://www.youtube.com/watch?v=PrZZfaDp02o
![cant-watch-it-on-youtube](https://cloud.githubusercontent.com/assets/194400/20177436/a4e37fe2-a744-11e6-9113-75e0ccfd5470.png)

_However_ the _same_ song is available on the `INXSVEVO`: https://www.youtube.com/watch?v=w-rv2BQa2OU 😉

**Comment by jxnblk** [comment]
Thanks for the heads up. I figured that would happen eventually. Might just remove the video altogether and make this look like a "real" site

**Comment by nelsonic** [comment]
Yeah, _removing_ the video is an _option_, 😞 
however you're helping to _educate_ "the next generation" in classic '80's tunes 🎵 
while teaching them the wonders of `Functional CSS`... seems like a good community service. 😉

**Comment by jxnblk** [comment]
Just noticed that the video still plays for me in NYC. Do you think maybe it's just blocked in certain countries?

**Comment by nelsonic** [comment]
@jxnblk yeah, absolutely it's blocked in certain countries because it's not an "official" version of the video. The `"Mystify"` channel looks like a "tribute" channel which was _probably_ created by someone who is a _fan_ of INXS whereas the other video is on the `INXSVEVO` which is a _verified_ channel (_meaning it belongs to the copyright holder_) so the family(s) of the band members get a royalty for the airplay... anyway, just thought I would mention it because I'm in Portugal (_for [`#WebSummit`](https://websummit.net/) ..._) and the video is "blocked" in this region ... 😞
